# @format

spring:
  profiles.active: dev
  main.allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
logging.level.org.springframework: OFF
logging.level.com.alokmeds.api: ERROR
logging:
  file:
    name: app.log