# @format

spring.jpa:
  show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  url: jdbc:postgresql://localhost:5433/test
  password: 123456
  username: postgres
alokmeds.security:
  jwtSecret: 8391374#$23eundjc#*#E*&jidHJBDCBU^&YEHB@$rUSHX#%^NUEDYG@#*#$tgver
spring.mail:
  username:
  password:
