# @format

spring.jpa:
  show-sql: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.datasource:
  url: jdbc:postgresql://localhost:5433/postgres
  password: 123456
  username: postgres
spring:
  jpa:
    show-sql: false
alokmeds.security:
  cookieLife: 600
  cookieName: token
  jwtSecret: ayush
spring.mail:
  username:
  password: 