# @format

spring.jpa:
  show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  url: jdbc:postgresql://localhost:5433/test
  password: 123456
  username: postgres
spring.mail:
  username: ayushalokdubey@gmail.com
  password: bfpzdcekvgqbbkwy

alokmeds.security:
  cookieLife: 600
  cookieName: token
  jwtSecret: 8391374#$23eundjc#*#E*&jidHJBDCBU^&YEHB@$rUSHX#%^NUEDYG@#*#$tgver