# @format

spring.jpa:
  show-sql: false
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  url: ${DATABASE_URL}
alokmeds.security:
  jwtSecret: ${JWT_SECRET}
spring.mail:
  username: ayushalokdubey@gmail.com
  password: bfpzdcekvgqbbkwy
